// Extended mock data for all categories
import { Product } from './data';

// Vehicle listings
export const vehicleProducts: Product[] = [
  {
    id: 'v1',
    title: 'Toyota Corolla 2019 - Very Clean',
    description: 'Well maintained Toyota Corolla, single owner, full service history. AC working perfectly, new tires.',
    price: 45000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800'],
    categoryId: 'vehicles',
    subcategoryId: 'cars',
    sellerId: 'seller1',
    sellerName: 'John Mwamba',
    sellerVerified: true,
    location: 'Kinondoni',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: true,
    promoted: true,
    views: 234,
    favorites: 45,
    status: 'active',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'v2',
    title: 'Honda Fit 2020 - Low Mileage',
    description: 'Excellent condition Honda Fit, automatic transmission, very economical on fuel.',
    price: 32000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800'],
    categoryId: 'vehicles',
    subcategoryId: 'cars',
    sellerId: 'seller2',
    sellerName: 'AutoMart TZ',
    sellerVerified: true,
    location: 'Ilala',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 189,
    favorites: 32,
    status: 'active',
    createdAt: '2024-01-14T09:00:00Z',
    updatedAt: '2024-01-14T09:00:00Z',
  },
  {
    id: 'v3',
    title: 'Toyota Land Cruiser Prado 2018',
    description: 'Powerful 4x4 SUV, perfect for Tanzanian roads. Diesel engine, leather interior.',
    price: 95000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800'],
    categoryId: 'vehicles',
    subcategoryId: 'cars',
    sellerId: 'seller3',
    sellerName: 'Premium Motors',
    sellerVerified: true,
    location: 'Masaki',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 456,
    favorites: 89,
    status: 'active',
    createdAt: '2024-01-13T14:00:00Z',
    updatedAt: '2024-01-13T14:00:00Z',
  },
  {
    id: 'v4',
    title: 'Honda CBR 600RR Motorcycle',
    description: 'Sport bike in excellent condition, low mileage, recently serviced.',
    price: 18000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
    categoryId: 'vehicles',
    subcategoryId: 'motorcycles',
    sellerId: 'seller5',
    sellerName: 'Speed Motors',
    sellerVerified: true,
    location: 'Mikocheni',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 178,
    favorites: 45,
    status: 'active',
    createdAt: '2024-01-10T16:00:00Z',
    updatedAt: '2024-01-10T16:00:00Z',
  },
  {
    id: 'v5',
    title: 'Bajaj Boxer 150cc - Brand New',
    description: 'Brand new Bajaj Boxer, perfect for city commuting. Warranty included.',
    price: 3500000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800'],
    categoryId: 'vehicles',
    subcategoryId: 'motorcycles',
    sellerId: 'seller6',
    sellerName: 'Bajaj Tanzania',
    sellerVerified: true,
    location: 'Ubungo',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: false,
    promoted: false,
    views: 234,
    favorites: 67,
    status: 'active',
    createdAt: '2024-01-09T11:00:00Z',
    updatedAt: '2024-01-09T11:00:00Z',
  },
  {
    id: 'v6',
    title: 'Isuzu FRR Truck 2017',
    description: 'Heavy duty truck suitable for construction and logistics. Good condition.',
    price: 75000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800'],
    categoryId: 'vehicles',
    subcategoryId: 'trucks',
    sellerId: 'seller7',
    sellerName: 'Heavy Equipment TZ',
    sellerVerified: true,
    location: 'Temeke',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 98,
    favorites: 12,
    status: 'active',
    createdAt: '2024-01-08T08:00:00Z',
    updatedAt: '2024-01-08T08:00:00Z',
  },
  {
    id: 'v7',
    title: 'Mercedes Benz C200 2021',
    description: 'Luxury sedan, fully loaded with all features. Pearl white color.',
    price: 120000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800'],
    categoryId: 'vehicles',
    subcategoryId: 'cars',
    sellerId: 'seller8',
    sellerName: 'Luxury Cars TZ',
    sellerVerified: true,
    location: 'Oyster Bay',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: true,
    promoted: true,
    views: 567,
    favorites: 123,
    status: 'active',
    createdAt: '2024-01-07T15:00:00Z',
    updatedAt: '2024-01-07T15:00:00Z',
  },
  {
    id: 'v8',
    title: 'Nissan X-Trail 2019 - 7 Seater',
    description: 'Family SUV with 3rd row seating. Perfect for large families.',
    price: 55000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800'],
    categoryId: 'vehicles',
    subcategoryId: 'cars',
    sellerId: 'seller1',
    sellerName: 'John Mwamba',
    sellerVerified: true,
    location: 'Mbezi Beach',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 145,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-06T10:00:00Z',
    updatedAt: '2024-01-06T10:00:00Z',
  },
];

// Electronics listings
export const electronicsProducts: Product[] = [
  {
    id: 'e1',
    title: 'iPhone 14 Pro Max 256GB',
    description: 'Brand new iPhone 14 Pro Max, sealed in box. International warranty included.',
    price: 3200000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800'],
    categoryId: 'electronics',
    subcategoryId: 'phones',
    sellerId: 'seller2',
    sellerName: 'TechHub Tanzania',
    sellerVerified: true,
    location: 'Masaki',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: true,
    promoted: true,
    views: 567,
    favorites: 89,
    status: 'active',
    createdAt: '2024-01-14T08:30:00Z',
    updatedAt: '2024-01-14T08:30:00Z',
  },
  {
    id: 'e2',
    title: 'Samsung Galaxy S23 Ultra',
    description: 'Latest Samsung flagship phone with S-Pen. 512GB storage.',
    price: 2800000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800'],
    categoryId: 'electronics',
    subcategoryId: 'phones',
    sellerId: 'seller2',
    sellerName: 'TechHub Tanzania',
    sellerVerified: true,
    location: 'Masaki',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 423,
    favorites: 67,
    status: 'active',
    createdAt: '2024-01-13T11:00:00Z',
    updatedAt: '2024-01-13T11:00:00Z',
  },
  {
    id: 'e3',
    title: 'Samsung 55" Smart TV 4K',
    description: 'Brand new Samsung Smart TV, 4K UHD resolution, built-in Netflix and YouTube apps.',
    price: 1800000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800'],
    categoryId: 'electronics',
    subcategoryId: 'tvs',
    sellerId: 'seller2',
    sellerName: 'TechHub Tanzania',
    sellerVerified: true,
    location: 'Masaki',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 345,
    favorites: 67,
    status: 'active',
    createdAt: '2024-01-11T11:30:00Z',
    updatedAt: '2024-01-11T11:30:00Z',
  },
  {
    id: 'e4',
    title: 'MacBook Pro M2 14-inch',
    description: 'Apple MacBook Pro with M2 chip, 16GB RAM, 512GB SSD. Perfect for professionals.',
    price: 4500000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800'],
    categoryId: 'electronics',
    subcategoryId: 'computers',
    sellerId: 'seller9',
    sellerName: 'Apple Store TZ',
    sellerVerified: true,
    location: 'Mlimani City',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: true,
    promoted: true,
    views: 678,
    favorites: 145,
    status: 'active',
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-01-12T09:00:00Z',
  },
  {
    id: 'e5',
    title: 'HP Pavilion Gaming Laptop',
    description: 'Gaming laptop with RTX 3060, Intel i7, 16GB RAM. Great for gaming and work.',
    price: 2500000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800'],
    categoryId: 'electronics',
    subcategoryId: 'computers',
    sellerId: 'seller10',
    sellerName: 'Gaming Zone TZ',
    sellerVerified: true,
    location: 'Kariakoo',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 234,
    favorites: 56,
    status: 'active',
    createdAt: '2024-01-10T14:00:00Z',
    updatedAt: '2024-01-10T14:00:00Z',
  },
  {
    id: 'e6',
    title: 'Sony WH-1000XM5 Headphones',
    description: 'Premium noise-canceling wireless headphones. Best in class audio quality.',
    price: 850000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'],
    categoryId: 'electronics',
    subcategoryId: 'accessories',
    sellerId: 'seller2',
    sellerName: 'TechHub Tanzania',
    sellerVerified: true,
    location: 'Masaki',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: false,
    promoted: false,
    views: 123,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-09T16:00:00Z',
    updatedAt: '2024-01-09T16:00:00Z',
  },
  {
    id: 'e7',
    title: 'PS5 Console with 2 Controllers',
    description: 'PlayStation 5 disc edition with extra controller and 3 games included.',
    price: 1900000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800'],
    categoryId: 'electronics',
    subcategoryId: 'accessories',
    sellerId: 'seller10',
    sellerName: 'Gaming Zone TZ',
    sellerVerified: true,
    location: 'Kariakoo',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 456,
    favorites: 89,
    status: 'active',
    createdAt: '2024-01-08T12:00:00Z',
    updatedAt: '2024-01-08T12:00:00Z',
  },
  {
    id: 'e8',
    title: 'Tecno Spark 10 Pro',
    description: 'Budget smartphone with great camera. 8GB RAM, 128GB storage.',
    price: 450000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800'],
    categoryId: 'electronics',
    subcategoryId: 'phones',
    sellerId: 'seller11',
    sellerName: 'Mobile World',
    sellerVerified: false,
    location: 'Posta',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 234,
    favorites: 45,
    status: 'active',
    createdAt: '2024-01-07T10:00:00Z',
    updatedAt: '2024-01-07T10:00:00Z',
  },
];

// Property listings
export const propertyProducts: Product[] = [
  {
    id: 'p1',
    title: '3 Bedroom House for Sale - Mbezi Beach',
    description: 'Beautiful 3 bedroom house with modern finishes. Large compound, swimming pool, generator backup.',
    price: 450000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'],
    categoryId: 'property',
    subcategoryId: 'houses',
    sellerId: 'seller3',
    sellerName: 'Prime Properties TZ',
    sellerVerified: true,
    location: 'Mbezi Beach',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: true,
    views: 123,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-13T14:00:00Z',
    updatedAt: '2024-01-13T14:00:00Z',
  },
  {
    id: 'p2',
    title: '2 Bedroom Apartment - Masaki',
    description: 'Luxury apartment with ocean view. 24hr security, parking, gym access included.',
    price: 180000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    categoryId: 'property',
    subcategoryId: 'apartments',
    sellerId: 'seller3',
    sellerName: 'Prime Properties TZ',
    sellerVerified: true,
    location: 'Masaki',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 456,
    favorites: 89,
    status: 'active',
    createdAt: '2024-01-12T11:00:00Z',
    updatedAt: '2024-01-12T11:00:00Z',
  },
  {
    id: 'p3',
    title: '1 Acre Land for Sale - Bagamoyo',
    description: 'Prime land with title deed. Perfect for residential or commercial development.',
    price: 80000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    categoryId: 'property',
    subcategoryId: 'land',
    sellerId: 'seller12',
    sellerName: 'Land Solutions TZ',
    sellerVerified: true,
    location: 'Bagamoyo',
    region: 'Pwani',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 234,
    favorites: 56,
    status: 'active',
    createdAt: '2024-01-11T09:00:00Z',
    updatedAt: '2024-01-11T09:00:00Z',
  },
  {
    id: 'p4',
    title: 'Office Space for Rent - CBD',
    description: '500sqm office space in prime CBD location. All amenities included.',
    price: 15000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
    categoryId: 'property',
    subcategoryId: 'commercial',
    sellerId: 'seller13',
    sellerName: 'Commercial Realty',
    sellerVerified: true,
    location: 'CBD',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 156,
    favorites: 23,
    status: 'active',
    createdAt: '2024-01-10T15:00:00Z',
    updatedAt: '2024-01-10T15:00:00Z',
  },
  {
    id: 'p5',
    title: '4 Bedroom Villa - Oyster Bay',
    description: 'Luxurious villa with sea view. Garden, servants quarters, modern kitchen.',
    price: 850000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
    categoryId: 'property',
    subcategoryId: 'houses',
    sellerId: 'seller3',
    sellerName: 'Prime Properties TZ',
    sellerVerified: true,
    location: 'Oyster Bay',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: true,
    views: 678,
    favorites: 145,
    status: 'active',
    createdAt: '2024-01-09T12:00:00Z',
    updatedAt: '2024-01-09T12:00:00Z',
  },
  {
    id: 'p6',
    title: 'Studio Apartment for Rent - Mikocheni',
    description: 'Cozy studio apartment, fully furnished. Bills included. Monthly rent.',
    price: 800000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    categoryId: 'property',
    subcategoryId: 'apartments',
    sellerId: 'seller14',
    sellerName: 'Rental Hub',
    sellerVerified: false,
    location: 'Mikocheni',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: false,
    featured: false,
    promoted: false,
    views: 345,
    favorites: 67,
    status: 'active',
    createdAt: '2024-01-08T14:00:00Z',
    updatedAt: '2024-01-08T14:00:00Z',
  },
  {
    id: 'p7',
    title: 'Plot for Sale - Kigamboni',
    description: 'Half acre plot with clean title. Near the beach, great investment opportunity.',
    price: 45000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800'],
    categoryId: 'property',
    subcategoryId: 'land',
    sellerId: 'seller12',
    sellerName: 'Land Solutions TZ',
    sellerVerified: true,
    location: 'Kigamboni',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 189,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-07T08:00:00Z',
    updatedAt: '2024-01-07T08:00:00Z',
  },
  {
    id: 'p8',
    title: 'Warehouse for Rent - Ubungo',
    description: '2000sqm warehouse with loading bay. Ideal for logistics and storage.',
    price: 8000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800'],
    categoryId: 'property',
    subcategoryId: 'commercial',
    sellerId: 'seller13',
    sellerName: 'Commercial Realty',
    sellerVerified: true,
    location: 'Ubungo',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 123,
    favorites: 18,
    status: 'active',
    createdAt: '2024-01-06T11:00:00Z',
    updatedAt: '2024-01-06T11:00:00Z',
  },
];

// Fashion listings
export const fashionProducts: Product[] = [
  {
    id: 'f1',
    title: 'Kitenge Dress - African Print Fashion',
    description: 'Beautiful handmade kitenge dress, available in multiple sizes. High quality African print fabric.',
    price: 85000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=800'],
    categoryId: 'fashion',
    subcategoryId: 'womens',
    sellerId: 'seller4',
    sellerName: 'Mama Africa Fashions',
    sellerVerified: false,
    location: 'Kariakoo',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 89,
    favorites: 23,
    status: 'active',
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-01-12T09:00:00Z',
  },
  {
    id: 'f2',
    title: 'Nike Air Jordan 1 - Size 43',
    description: 'Authentic Nike Air Jordan 1 sneakers. Brand new in box.',
    price: 380000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800'],
    categoryId: 'fashion',
    subcategoryId: 'shoes',
    sellerId: 'seller15',
    sellerName: 'Sneaker World TZ',
    sellerVerified: true,
    location: 'Mlimani City',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: true,
    promoted: true,
    views: 456,
    favorites: 89,
    status: 'active',
    createdAt: '2024-01-11T14:00:00Z',
    updatedAt: '2024-01-11T14:00:00Z',
  },
  {
    id: 'f3',
    title: 'Designer Leather Handbag',
    description: 'Genuine leather handbag, imported from Italy. Multiple compartments.',
    price: 250000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800'],
    categoryId: 'fashion',
    subcategoryId: 'bags',
    sellerId: 'seller16',
    sellerName: 'Luxury Boutique',
    sellerVerified: true,
    location: 'Masaki',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 234,
    favorites: 56,
    status: 'active',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'f4',
    title: "Men's Formal Suit - Navy Blue",
    description: 'High quality formal suit, perfect for business meetings and events. Size M-XXL available.',
    price: 350000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800'],
    categoryId: 'fashion',
    subcategoryId: 'mens',
    sellerId: 'seller17',
    sellerName: 'Executive Wear',
    sellerVerified: true,
    location: 'Posta',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 178,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-09T15:00:00Z',
    updatedAt: '2024-01-09T15:00:00Z',
  },
  {
    id: 'f5',
    title: 'Traditional Maasai Jewelry Set',
    description: 'Authentic Maasai beadwork necklace and earrings. Handcrafted by local artisans.',
    price: 120000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800'],
    categoryId: 'fashion',
    subcategoryId: 'bags',
    sellerId: 'seller18',
    sellerName: 'Maasai Crafts',
    sellerVerified: false,
    location: 'Arusha',
    region: 'Arusha',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 145,
    favorites: 45,
    status: 'active',
    createdAt: '2024-01-08T09:00:00Z',
    updatedAt: '2024-01-08T09:00:00Z',
  },
  {
    id: 'f6',
    title: "Women's Ankara Jumpsuit",
    description: 'Stylish African print jumpsuit. Perfect for casual and semi-formal occasions.',
    price: 95000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800'],
    categoryId: 'fashion',
    subcategoryId: 'womens',
    sellerId: 'seller4',
    sellerName: 'Mama Africa Fashions',
    sellerVerified: false,
    location: 'Kariakoo',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 123,
    favorites: 28,
    status: 'active',
    createdAt: '2024-01-07T12:00:00Z',
    updatedAt: '2024-01-07T12:00:00Z',
  },
  {
    id: 'f7',
    title: 'Timberland Boots - Original',
    description: 'Classic Timberland boots, waterproof. Size 40-45 available.',
    price: 450000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800'],
    categoryId: 'fashion',
    subcategoryId: 'shoes',
    sellerId: 'seller15',
    sellerName: 'Sneaker World TZ',
    sellerVerified: true,
    location: 'Mlimani City',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 234,
    favorites: 67,
    status: 'active',
    createdAt: '2024-01-06T14:00:00Z',
    updatedAt: '2024-01-06T14:00:00Z',
  },
  {
    id: 'f8',
    title: 'Vintage Denim Jacket',
    description: 'Classic denim jacket, unisex style. Perfect for cool evenings.',
    price: 75000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800'],
    categoryId: 'fashion',
    subcategoryId: 'mens',
    sellerId: 'seller19',
    sellerName: 'Vintage Store',
    sellerVerified: false,
    location: 'Mwenge',
    region: 'Dar es Salaam',
    condition: 'used',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 89,
    favorites: 19,
    status: 'active',
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
];

// Home & Garden listings
export const homeProducts: Product[] = [
  {
    id: 'h1',
    title: 'Modern Office Desk with Chair',
    description: 'Executive office desk with ergonomic chair. Perfect for home office or business.',
    price: 450000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800'],
    categoryId: 'home',
    subcategoryId: 'furniture',
    sellerId: 'seller6',
    sellerName: 'Furniture Palace',
    sellerVerified: true,
    location: 'Posta',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 67,
    favorites: 12,
    status: 'active',
    createdAt: '2024-01-09T13:00:00Z',
    updatedAt: '2024-01-09T13:00:00Z',
  },
  {
    id: 'h2',
    title: 'L-Shaped Sofa Set - Italian Leather',
    description: 'Luxury leather sofa set, seats 6-7 people comfortably. Includes coffee table.',
    price: 2500000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'],
    categoryId: 'home',
    subcategoryId: 'furniture',
    sellerId: 'seller6',
    sellerName: 'Furniture Palace',
    sellerVerified: true,
    location: 'Posta',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: true,
    views: 345,
    favorites: 78,
    status: 'active',
    createdAt: '2024-01-08T11:00:00Z',
    updatedAt: '2024-01-08T11:00:00Z',
  },
  {
    id: 'h3',
    title: 'Samsung Double Door Refrigerator',
    description: '500L capacity, inverter technology, water dispenser included.',
    price: 1800000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800'],
    categoryId: 'home',
    subcategoryId: 'appliances',
    sellerId: 'seller20',
    sellerName: 'Home Appliances TZ',
    sellerVerified: true,
    location: 'Mlimani City',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 234,
    favorites: 56,
    status: 'active',
    createdAt: '2024-01-07T14:00:00Z',
    updatedAt: '2024-01-07T14:00:00Z',
  },
  {
    id: 'h4',
    title: 'Garden Furniture Set - 6 Seater',
    description: 'Weather-resistant outdoor furniture set with cushions and umbrella.',
    price: 850000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800'],
    categoryId: 'home',
    subcategoryId: 'garden',
    sellerId: 'seller21',
    sellerName: 'Garden World',
    sellerVerified: false,
    location: 'Mbezi Beach',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 123,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-06T09:00:00Z',
    updatedAt: '2024-01-06T09:00:00Z',
  },
  {
    id: 'h5',
    title: 'Complete Kitchen Cabinet Set',
    description: 'Modern kitchen cabinets with granite countertop. Installation included.',
    price: 3500000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800'],
    categoryId: 'home',
    subcategoryId: 'kitchen',
    sellerId: 'seller22',
    sellerName: 'Kitchen Masters',
    sellerVerified: true,
    location: 'Kinondoni',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: false,
    views: 189,
    favorites: 45,
    status: 'active',
    createdAt: '2024-01-05T15:00:00Z',
    updatedAt: '2024-01-05T15:00:00Z',
  },
  {
    id: 'h6',
    title: 'LG Washing Machine - 8kg',
    description: 'Front load washing machine with steam wash function. Energy efficient.',
    price: 950000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800'],
    categoryId: 'home',
    subcategoryId: 'appliances',
    sellerId: 'seller20',
    sellerName: 'Home Appliances TZ',
    sellerVerified: true,
    location: 'Mlimani City',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 156,
    favorites: 28,
    status: 'active',
    createdAt: '2024-01-04T10:00:00Z',
    updatedAt: '2024-01-04T10:00:00Z',
  },
  {
    id: 'h7',
    title: 'King Size Bed with Mattress',
    description: 'Solid wood bed frame with orthopedic mattress. Excellent quality.',
    price: 1200000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800'],
    categoryId: 'home',
    subcategoryId: 'furniture',
    sellerId: 'seller6',
    sellerName: 'Furniture Palace',
    sellerVerified: true,
    location: 'Posta',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 267,
    favorites: 67,
    status: 'active',
    createdAt: '2024-01-03T12:00:00Z',
    updatedAt: '2024-01-03T12:00:00Z',
  },
  {
    id: 'h8',
    title: 'Split Air Conditioner - 24000 BTU',
    description: 'Powerful cooling for large rooms. Energy efficient inverter technology.',
    price: 1400000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800'],
    categoryId: 'home',
    subcategoryId: 'appliances',
    sellerId: 'seller20',
    sellerName: 'Home Appliances TZ',
    sellerVerified: true,
    location: 'Mlimani City',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 189,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-02T09:00:00Z',
    updatedAt: '2024-01-02T09:00:00Z',
  },
];

// Jobs listings
export const jobProducts: Product[] = [
  {
    id: 'j1',
    title: 'Software Developer - Full Time',
    description: 'Looking for experienced React/Node.js developer. Remote work possible. Competitive salary.',
    price: 2500000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800'],
    categoryId: 'jobs',
    subcategoryId: 'fulltime',
    sellerId: 'seller23',
    sellerName: 'TechCorp Tanzania',
    sellerVerified: true,
    location: 'Masaki',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: true,
    views: 567,
    favorites: 123,
    status: 'active',
    createdAt: '2024-01-14T08:00:00Z',
    updatedAt: '2024-01-14T08:00:00Z',
  },
  {
    id: 'j2',
    title: 'Marketing Manager - Dar es Salaam',
    description: 'Established company seeking marketing manager with 5+ years experience.',
    price: 3000000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1552664730-d307ca884978?w=800'],
    categoryId: 'jobs',
    subcategoryId: 'fulltime',
    sellerId: 'seller24',
    sellerName: 'Global Brands TZ',
    sellerVerified: true,
    location: 'CBD',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: true,
    promoted: false,
    views: 345,
    favorites: 78,
    status: 'active',
    createdAt: '2024-01-13T10:00:00Z',
    updatedAt: '2024-01-13T10:00:00Z',
  },
  {
    id: 'j3',
    title: 'Part-Time Accountant Needed',
    description: 'Small business seeking part-time accountant. Flexible hours. CPA preferred.',
    price: 800000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800'],
    categoryId: 'jobs',
    subcategoryId: 'parttime',
    sellerId: 'seller25',
    sellerName: 'SME Solutions',
    sellerVerified: false,
    location: 'Ilala',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 234,
    favorites: 56,
    status: 'active',
    createdAt: '2024-01-12T14:00:00Z',
    updatedAt: '2024-01-12T14:00:00Z',
  },
  {
    id: 'j4',
    title: 'Graphic Designer - Freelance',
    description: 'Need talented graphic designer for ongoing projects. Portfolio required.',
    price: 500000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800'],
    categoryId: 'jobs',
    subcategoryId: 'freelance',
    sellerId: 'seller26',
    sellerName: 'Creative Agency',
    sellerVerified: true,
    location: 'Mikocheni',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 189,
    favorites: 45,
    status: 'active',
    createdAt: '2024-01-11T11:00:00Z',
    updatedAt: '2024-01-11T11:00:00Z',
  },
  {
    id: 'j5',
    title: 'Engineering Internship - 6 Months',
    description: 'Great opportunity for engineering students. Training provided. Stipend included.',
    price: 300000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800'],
    categoryId: 'jobs',
    subcategoryId: 'internships',
    sellerId: 'seller27',
    sellerName: 'Industrial Corp',
    sellerVerified: true,
    location: 'Ubungo',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: true,
    promoted: false,
    views: 456,
    favorites: 89,
    status: 'active',
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-10T09:00:00Z',
  },
  {
    id: 'j6',
    title: 'Sales Representative - Commission Based',
    description: 'High earning potential for motivated sales professionals. Training provided.',
    price: 0,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1556745757-8d76bdb6984b?w=800'],
    categoryId: 'jobs',
    subcategoryId: 'fulltime',
    sellerId: 'seller28',
    sellerName: 'Sales Force TZ',
    sellerVerified: true,
    location: 'Kinondoni',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: false,
    promoted: true,
    views: 278,
    favorites: 67,
    status: 'active',
    createdAt: '2024-01-09T15:00:00Z',
    updatedAt: '2024-01-09T15:00:00Z',
  },
  {
    id: 'j7',
    title: 'Content Writer - Remote',
    description: 'Looking for creative content writers. Swahili and English fluency required.',
    price: 600000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800'],
    categoryId: 'jobs',
    subcategoryId: 'freelance',
    sellerId: 'seller29',
    sellerName: 'Digital Media TZ',
    sellerVerified: false,
    location: 'Remote',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 156,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-08T12:00:00Z',
    updatedAt: '2024-01-08T12:00:00Z',
  },
  {
    id: 'j8',
    title: 'Hotel Receptionist - Zanzibar',
    description: 'Beach resort hiring receptionists. Accommodation provided. Experience preferred.',
    price: 800000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    categoryId: 'jobs',
    subcategoryId: 'fulltime',
    sellerId: 'seller30',
    sellerName: 'Paradise Resort',
    sellerVerified: true,
    location: 'Stone Town',
    region: 'Zanzibar',
    condition: 'new',
    negotiable: false,
    featured: false,
    promoted: false,
    views: 345,
    favorites: 78,
    status: 'active',
    createdAt: '2024-01-07T10:00:00Z',
    updatedAt: '2024-01-07T10:00:00Z',
  },
];

// Services listings
export const serviceProducts: Product[] = [
  {
    id: 's1',
    title: 'Professional House Cleaning Service',
    description: 'Thorough house cleaning by trained staff. Weekly, bi-weekly or one-time service available.',
    price: 50000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800'],
    categoryId: 'services',
    subcategoryId: 'cleaning',
    sellerId: 'seller31',
    sellerName: 'Clean Home Services',
    sellerVerified: true,
    location: 'All Dar es Salaam',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: true,
    views: 456,
    favorites: 89,
    status: 'active',
    createdAt: '2024-01-14T08:00:00Z',
    updatedAt: '2024-01-14T08:00:00Z',
  },
  {
    id: 's2',
    title: 'AC Repair & Installation',
    description: 'Expert AC technicians. All brands serviced. Same-day service available.',
    price: 30000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800'],
    categoryId: 'services',
    subcategoryId: 'repair',
    sellerId: 'seller32',
    sellerName: 'Cool Tech Solutions',
    sellerVerified: true,
    location: 'Dar es Salaam',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: true,
    promoted: false,
    views: 345,
    favorites: 67,
    status: 'active',
    createdAt: '2024-01-13T11:00:00Z',
    updatedAt: '2024-01-13T11:00:00Z',
  },
  {
    id: 's3',
    title: 'English Language Classes',
    description: 'Learn English from native speakers. Online and in-person classes available.',
    price: 150000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800'],
    categoryId: 'services',
    subcategoryId: 'education',
    sellerId: 'seller33',
    sellerName: 'Language Academy',
    sellerVerified: true,
    location: 'Mlimani City',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 234,
    favorites: 56,
    status: 'active',
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-01-12T09:00:00Z',
  },
  {
    id: 's4',
    title: 'Wedding Photography & Videography',
    description: 'Professional wedding coverage. Drone shots included. 10+ years experience.',
    price: 1500000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1519741497674-611481863552?w=800'],
    categoryId: 'services',
    subcategoryId: 'events',
    sellerId: 'seller34',
    sellerName: 'Moments Studio',
    sellerVerified: true,
    location: 'All Tanzania',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: true,
    promoted: true,
    views: 567,
    favorites: 123,
    status: 'active',
    createdAt: '2024-01-11T14:00:00Z',
    updatedAt: '2024-01-11T14:00:00Z',
  },
  {
    id: 's5',
    title: 'Plumbing Services - 24/7',
    description: 'Emergency plumbing repairs. Leaks, blockages, installations. Fast response.',
    price: 25000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800'],
    categoryId: 'services',
    subcategoryId: 'repair',
    sellerId: 'seller35',
    sellerName: 'Quick Fix Plumbing',
    sellerVerified: false,
    location: 'Dar es Salaam',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 189,
    favorites: 34,
    status: 'active',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 's6',
    title: 'Private Tutoring - NECTA Prep',
    description: 'Experienced teachers for Form 4 & Form 6 exam preparation. All subjects.',
    price: 80000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800'],
    categoryId: 'services',
    subcategoryId: 'education',
    sellerId: 'seller36',
    sellerName: 'Excel Tutors',
    sellerVerified: true,
    location: 'Kinondoni',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: true,
    views: 345,
    favorites: 78,
    status: 'active',
    createdAt: '2024-01-09T15:00:00Z',
    updatedAt: '2024-01-09T15:00:00Z',
  },
  {
    id: 's7',
    title: 'Event DJ & Sound System Rental',
    description: 'Professional DJ services for weddings, parties, and corporate events.',
    price: 300000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800'],
    categoryId: 'services',
    subcategoryId: 'events',
    sellerId: 'seller37',
    sellerName: 'Party Vibes Entertainment',
    sellerVerified: true,
    location: 'Dar es Salaam',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: true,
    featured: false,
    promoted: false,
    views: 234,
    favorites: 56,
    status: 'active',
    createdAt: '2024-01-08T12:00:00Z',
    updatedAt: '2024-01-08T12:00:00Z',
  },
  {
    id: 's8',
    title: 'Car Wash & Detailing - Mobile Service',
    description: 'We come to you! Full car wash and interior detailing at your location.',
    price: 35000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=800'],
    categoryId: 'services',
    subcategoryId: 'cleaning',
    sellerId: 'seller38',
    sellerName: 'Shine Mobile Wash',
    sellerVerified: false,
    location: 'Dar es Salaam',
    region: 'Dar es Salaam',
    condition: 'new',
    negotiable: false,
    featured: false,
    promoted: false,
    views: 156,
    favorites: 28,
    status: 'active',
    createdAt: '2024-01-07T09:00:00Z',
    updatedAt: '2024-01-07T09:00:00Z',
  },
];

// Get all products by category
export function getProductsByCategory(categorySlug: string): Product[] {
  switch (categorySlug) {
    case 'vehicles':
      return vehicleProducts;
    case 'electronics':
      return electronicsProducts;
    case 'property':
      return propertyProducts;
    case 'fashion':
      return fashionProducts;
    case 'home':
      return homeProducts;
    case 'jobs':
      return jobProducts;
    case 'services':
      return serviceProducts;
    default:
      return [];
  }
}

// Get all products
export function getAllProducts(): Product[] {
  return [
    ...vehicleProducts,
    ...electronicsProducts,
    ...propertyProducts,
    ...fashionProducts,
    ...homeProducts,
    ...jobProducts,
    ...serviceProducts,
  ];
}
